server:
  port: 8080
spring:
  profiles:
    #    外置jdbc,redis,mail配置文件
    active: jdbc,redis,mail
  #    关闭thymeleaf缓存
  thymeleaf:
    cache: false
  #    配置国际化资源文件
  messages:
    basename: i18n.logo
  devtools:
    restart:
      enabled: true

mybatis:
  configuration:
    # 开启驼峰命名匹配映射
    map-underscore-to-camel-case: true
    #    输出sql执行语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.tianll.blog.model.domain
  mapper-locations: classpath:mapper/*.xml


#    pagehelper分页设置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#浏览器cookie默认时间30分钟
COOKIE:
  VALIDITY: 1800
